
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:subscription-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube:admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-policy-generator-demo
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kustomize-policy-generator-demo
  namespace: kustomize-policy-generator-demo
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kustomize-policy-generator-demo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: kustomize-policy-generator-demo
  namespace: kustomize-policy-generator-demo
spec:
  type: Git
  pathname: https://github.com/dhaiducek/kustomize-it.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: kustomize-policy-generator-demo
  name: kustomize-policy-generator-demo-subscription
  namespace: kustomize-policy-generator-demo
spec:
  channel: kustomize-policy-generator-demo/kustomize-policy-generator-demo
  placement:
    placementRef:
      kind: PlacementRule
      name: kustomize-policy-generator-demo-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: kustomize-policy-generator-demo
  name: kustomize-policy-generator-demo-placement
  namespace: kustomize-policy-generator-demo
spec:
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
